language: python
python:
  - "2.7"
before_install:
  - sudo apt-get update
  - sudo apt-get -y install python-pip
  - sudo pip install --upgrade pip
  - pip install --upgrade pip
  - pip install pep8
install:
  - pip install -r requirements.txt
script:
  - find . -name \*.py -exec pep8 --ignore=E402 {} +
